# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ABRE_COLCHETE', 'ABRE_PARENTESE', 'ATE', 'ATRIBUICAO', 'DIFERENTE', 'DIVIDE', 'DOIS_PONTOS', 'E', 'ENTAO', 'ESCREVA', 'FECHA_COLCHETE', 'FECHA_PARENTESE', 'FIM', 'FLUTUANTE', 'ID', 'IGUAL', 'INTEIRO', 'LEIA', 'MAIOR', 'MAIOR_IGUAL', 'MAIS', 'MENOR', 'MENOR_IGUAL', 'MENOS', 'NAO', 'NUM_INTEIRO', 'NUM_NOTACAO_CIENTIFICA', 'NUM_PONTO_FLUTUANTE', 'OU', 'REPITA', 'RETORNA', 'SE', 'SENAO', 'VEZES', 'VIRGULA'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_ID>(([a-zA-ZáÁãÃàÀéÉíÍóÓõÕ])(([0-9])+|_|([a-zA-ZáÁãÃàÀéÉíÍóÓõÕ]))*))|(?P<t_NUM_NOTACAO_CIENTIFICA>(([\\-\\+]?)([1-9])\\.([0-9])+[eE]([\\-\\+]?)([0-9])+))|(?P<t_NUM_PONTO_FLUTUANTE>\\d+[eE][-+]?\\d+|(\\.\\d+|\\d+\\.\\d*)([eE][-+]?\\d+)?)|(?P<t_NUM_INTEIRO>\\d+)|(?P<t_COMENTARIO>(\\{((.|\\n)*?)\\}))|(?P<t_newline>\\n+)|(?P<t_OU>\\|\\|)|(?P<t_MAIS>\\+)|(?P<t_VEZES>\\*)|(?P<t_ABRE_PARENTESE>\\()|(?P<t_FECHA_PARENTESE>\\))|(?P<t_ABRE_COLCHETE>\\[)|(?P<t_FECHA_COLCHETE>\\])|(?P<t_ATRIBUICAO>:=)|(?P<t_E>&&)|(?P<t_DIFERENTE><>)|(?P<t_MENOR_IGUAL><=)|(?P<t_MAIOR_IGUAL>>=)|(?P<t_MENOS>-)|(?P<t_DIVIDE>/)|(?P<t_VIRGULA>,)|(?P<t_DOIS_PONTOS>:)|(?P<t_NAO>!)|(?P<t_MENOR><)|(?P<t_MAIOR>>)|(?P<t_IGUAL>=)', [None, ('t_ID', 'ID'), None, None, None, None, None, ('t_NUM_NOTACAO_CIENTIFICA', 'NUM_NOTACAO_CIENTIFICA'), None, None, None, None, None, None, ('t_NUM_PONTO_FLUTUANTE', 'NUM_PONTO_FLUTUANTE'), None, None, ('t_NUM_INTEIRO', 'NUM_INTEIRO'), ('t_COMENTARIO', 'COMENTARIO'), None, None, None, ('t_newline', 'newline'), (None, 'OU'), (None, 'MAIS'), (None, 'VEZES'), (None, 'ABRE_PARENTESE'), (None, 'FECHA_PARENTESE'), (None, 'ABRE_COLCHETE'), (None, 'FECHA_COLCHETE'), (None, 'ATRIBUICAO'), (None, 'E'), (None, 'DIFERENTE'), (None, 'MENOR_IGUAL'), (None, 'MAIOR_IGUAL'), (None, 'MENOS'), (None, 'DIVIDE'), (None, 'VIRGULA'), (None, 'DOIS_PONTOS'), (None, 'NAO'), (None, 'MENOR'), (None, 'MAIOR'), (None, 'IGUAL')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
